name: CI
on:
  push:
    branches:
    - main
    - release/*
    - develop
    - feature/*
  pull_request:
    branches:
      - '*'

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.0', '8.1']
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: composer install --no-progress
    - name: Run phpunit
      run: ./lib/vendor/bin/phpunit

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: composer install --no-progress
    - name: Run PHPStan
      run: ./lib/vendor/bin/phpstan analyse --no-progress

  php_cs_fixer:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: composer install --no-progress
    - name: Run phpcs
      run: ./lib/vendor/bin/phpcs -p
